### ISSUE TITLE
Openshift Run CodeTogether without security context

### ISSUE THREAD

**Issue by hupling** [Genuitec/CodeTogether#363]
**Describe the bug**
If you want to run codetogether in openshift you need to add the following security context. In my company that is not allowed.

```yaml
apiVersion: v1
kind: SecurityContextConstraints
metadata:
  name: codetogether-scc
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
fsGroup:
  type: MustRunAs
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
```

**Solution**

[Support arbitrary user ids Openshift](https://docs.openshift.com/container-platform/4.9/openshift_images/create-images.html#images-create-guide-openshift_create-images)

You need to add the group root to the files/folders and give it the right permissions.

```Dockerfile
RUN chgrp -R 0 /some/directory && \
    chmod -R g=u /some/directory
```
I modified the permissions and it worked without security context. I am not sure if you need to update the permission for each of the following folders/files. Please can you update your Image on the [RedHatCatalog](https://catalog.redhat.com/software/containers/genuitec/codetogether/5fbbdc772937386820426f55)
```Dockerfile
FROM registry.connect.redhat.com/genuitec/codetogether
User root
RUN chgrp -R 0 /opt/codetogether &&       chmod -R g=u /opt/codetogether
RUN chgrp -R 0 /var/log &&   chmod -R g=u /var/log
RUN chgrp -R 0 /run /var/www /var/cache/nginx /etc/localtime /usr/bin/update-ca-trust /etc/pki  /usr/bin/prosody  /usr/lib64/prosody  /etc/prosody /run/prosody /var/lib/prosody &&        chmod -R g=u /run /var/www /var/cache/nginx /etc/localtime /usr/bin/update-ca-trust /etc/pki   /usr/bin/prosody /usr/lib64/prosody /etc/prosody /run/prosody /var/lib/prosody
```
