### ISSUE TITLE
Helm-Chart: Automatically Roll Deployments

### ISSUE THREAD

**Issue by hupling** [Genuitec/CodeTogether#369]
**Describe the bug**

If I change for example the sso config in the helm chart, so config isn't taken from the pod. The pod needs to be manual restarted. 

**Solution**

https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

```yml
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/coturn: {{ include (print $.Template.BasePath "/secret-coturn.yaml") . | sha256sum }}
        checksum/dashboard: {{ include (print $.Template.BasePath "/secret-dashboard.yaml") . | sha256sum }}
        checksum/license: {{ include (print $.Template.BasePath "/secret-license.yaml") . | sha256sum }}
        checksum/sso: {{ include (print $.Template.BasePath "/secret-sso.yaml") . | sha256sum }}
```
